### ISSUE TITLE
کار نکردن با Refined Twitter

### ISSUE THREAD

**Issue by ashkrosh** [mimalef70/fontara#10]
سلام و خسته نباشید بابت این افزونه
متاسفانه روی توییتر با اکستنشن محبوب Refined Twitter تداخل داره و نمیشه همزمان از هر دو استفاده کرد
https://github.com/sindresorhus/refined-twitter
امکانش هست بررسی کنید؟

سپاس

**Comment by mimalef70** [comment]
میشه بیشتر توضیح بدید و مشکلات رو با اسکرین شات نشون بدید؟

**Comment by mimalef70** [comment]
@ashkrosh  جان 
با خاموش کردم تنظیم فونت سیستمی در تنظیمان این افزونه مشکل حل میشه.
<img width="399" alt="screen shot 2018-08-29 at 3 31 24 pm" src="https://user-images.githubusercontent.com/17767869/44783830-e16e0100-aba0-11e8-8aac-5f70fc5de2f3.png">
