### ISSUE TITLE
درخواست ایجاد  github page برای معرفی افزونه

### ISSUE THREAD

**Issue by zoghal** [mimalef70/fontara#11]
درود محمد جان
ضمن تشکر بابت تمامی زحماتی که کشیدی الان باهاش پیپر دراپ باکس رو نگاه کردم آخ لذت بردم که نگو، عاااالی

فقط یک نکته:
من الان می‌خواستم این افزونه رو معرفی کنم به کسانی که داکیومنت پیپر من رو نگاه می‌کنند.
اما دیدم هر کسی ممکنه یک مرورگر داشته باشه خیلی ضایع است همه رو بخواهم لینک بدم اونجا

گفتم بیام پیشنهاد بدم تو گیت هاب پیج یک پیج ایجاد کنید تا ضمن معرفی خود افزونه و امکاناتی و قابلیت‌ها، لینک‌ نصب همه افزونه هم در دسترس قرار داشته باشد.
فعلا

**Comment by mimalef70** [comment]
سلام خدمت شما
خیلی ممنون از زحماتی که بابت فونت ها می کشید.

 در حال حاضر من سعی کردم یک مطلب ویرگول که لینک ها توش باشه ایجاد کنم که آدرسش این هست:
https://virgool.io/@mimalef70/fontara-font-changer-dvzsripy2669
و تو فکر یک صفحه گیت هاب هم از همون ابتدا بودم ولی متاسفانه نرسیدم. برای همین فعلن به همین پست ویرگول بسنده کردم. ولی کاملا حق با شماست. سعی میکنم به زودی یک پیج ایجاد کنم. 
پیروز باشید

**Comment by mimalef70** [comment]
این صفحه ساخته شد: https://mimalef70.github.io/fontara
