### ISSUE TITLE
پشتیبانی از سایت بی بی سی فارسی

### ISSUE THREAD

**Issue by Ali-Reza-Rezaee** [mimalef70/fontara#13]

**Comment by mimalef70** [comment]
فونت آرای گلوبال از بی بی سی فارسی پشتیبانی میکند. برای این کار وارد سایت بی بی سی شود و در پایین پاپ آپ فونت آرا آن را فعال کنید.
![Uploading Screen Shot 2019-01-11 at 3.24.00 PM.png…]()
