### ISSUE TITLE
افزودن پشتیبانی از گیت‌هاب

### ISSUE THREAD

**Issue by Hameds** [mimalef70/fontara#2]
<div dir="rtl">
یکی از سایت‌هایی که می‌شه به مجموعه سایت‌های افزونه اضافه‌اش کرد، همین گیت‌هابه. هم بخش readme پروژه‌ها و هم متن و عناوین issue ها از بخش‌هایی است که می‌شه قابلیت تغییر فونت رو براشون در نظر گرفت
</div>

**Comment by mimalef70** [comment]
@Hameds در راستای افزایش روحیه جمعی. 
<img width="802" alt="screen shot 2018-07-25 at 6 24 14 pm" src="https://user-images.githubusercontent.com/17767869/43205174-07435bb6-9038-11e8-9bcb-e5f7a9296f7b.png">
به زودی در نسخه جدید منتشرش میکنم.

**Comment by mimalef70** [comment]
مدیوم که از ابتدا پشتیبانی میصه دوست عزیز، لوگو سبزه ست در حال حاضر.

**Comment by saeedalipoor** [comment]
@mimalef70 
نمی‌دونم مشکل از کجا بود، ولی موقعی که اون کامنت رو گذاشتم مدیوم با همون فونت پیش‌فرض نمایش داده می‌شد. :|
خسته نباشید و دمتون گرم :)
