### ISSUE TITLE
درخواست پشتیبانی از سایت طرفدای

### ISSUE THREAD

**Issue by mohamadaliakbari** [mimalef70/fontara#20]
سلام

طرفداری با رنک الکسای 17 یکی از پربازدیدترین سایت های کاربر محور فارسی است.

اگر این امکان برای طرفداری نیز فرآهم شود از سمت کاربران طرفداری نیز مورد استقبال قرار خواهد گرفت:

https://www.tarafdari.com/node/1078997

**Comment by mimalef70** [comment]
سلام.

با تشکر از شما بابت معرفی این افزونه. 
در حال حاضر در نسخه ۳ این امکان وجود دارد و تمام سایت ها پوشش داده میشوند.

<img width="1275" alt="screen shot 2018-09-04 at 3 41 38 pm" src="https://user-images.githubusercontent.com/17767869/45028150-27bbd800-b059-11e8-9d2b-1e34f535d45b.png">
