### ISSUE TITLE
بلاک‌های افزودن ستون جدید،‌ در tweetdeck

### ISSUE THREAD

**Issue by saeedesmaili** [mimalef70/fontara#21]
فونت بلاک‌هایی که برای افزودن ستون جدید، یا دیدن پروفایل کاربرا و ... تو توییت‌دک نمایش داده میشه تغییر داده نمیشه:
![image](https://user-images.githubusercontent.com/13351748/45422317-2156dd00-b6a5-11e8-8db1-557960909e34.png)
![image](https://user-images.githubusercontent.com/13351748/45422260-f53b5c00-b6a4-11e8-9022-d8573b17fbe8.png)

**Comment by mimalef70** [comment]
ممنون سعید جان. ولی من این مشکل رو مشاهده نکردم. دوباره یه نگاه میندازی. شاید افزونه خاموش بوده یا ...

**Comment by saeedesmaili** [comment]
باز هم چک کردم و همچنان این مشکل هست
البته روی فایرفاکس درسته و روی کروم مشکلی که گفتم هست. روی دو تا سیستم مختلف تست کردم.

**Comment by saeedesmaili** [comment]
روی فایرفاکس هم درست نیست و این مرورگر هم همین مشکل رو داره البته

**Comment by mimalef70** [comment]
همچنان این مشکل پا برجاست؟ من مجدد چک کردم و مشکلی نبود. فونت آراتون آپدیته سعید جان؟

**Comment by saeedesmaili** [comment]
وقتی این کامنت رو می‌ذاشتم مشکل داشت، ولی الان درسته انگار
