### ISSUE TITLE
راست‌چینی نظرات اینستاگرام

### ISSUE THREAD

**Issue by neesti** [mimalef70/fontara#23]
<div dir=rtl>
سلام.
اگر ممکن است، در نسخهٔ جدید افزونه پشتیبانی از راست‌چین‌کردن جهت نمایشِ نظرات اینستاگرام را هم اضافه کنید. 
الان در نسخهٔ تحت وب ایستاگرام، نظرات از چپ به راست نمایش داده می‌شوند. 

خیلی متشکرم.

**Comment by mimalef70** [comment]
از اونجایی که با انجام این کار برای صفحاتی که زبان غیرفارسی دارن مشکل پیش میاد تقریبا نمیشه چنین کاری رو به درستی انجام داد.
