### ISSUE TITLE
نوشته‌های فارسی در ورژن جدید گوگل کلندر

### ISSUE THREAD

**Issue by saeedesmaili** [mimalef70/fontara#34]
گوگل کلندر ریدیزاین شده و تو صفحه اصلی، ایونت‌هایی که توضیحات فارسی دارن، فونت براشون اعمال نمیشه

**Comment by saeedesmaili** [comment]
![image](https://user-images.githubusercontent.com/13351748/51070370-5aa05900-1655-11e9-87bb-f18ee902318e.png)

**Comment by mimalef70** [comment]
مشکل رفع شده. ممنون
