### ISSUE TITLE
پشتیبانی از گوگل تسک

### ISSUE THREAD

**Issue by mimalef70** [mimalef70/fontara#38]

**Comment by Masiha** [comment]
این موردی بود که می‌خواستم به آن اشاره کنم:
در جیمیل جدید، ستون سمت  راست، افزونه‌هایی مثل گوگل نت و گوگل تسک وجود دارند، در متن جیمیل، فونت‌آرا فعال است ولی در گوگل تسک، نیست.

**Comment by mimalef70** [comment]
در نسخه جدید این امکان اضافه شده.
