### ISSUE TITLE
تداخل متن توییت و شمارنده کاراکتر

### ISSUE THREAD

**Issue by Ssisakhti** [mimalef70/fontara#4]
![fdsfdsfds](https://user-images.githubusercontent.com/3183983/43339825-ac70b7ce-91ef-11e8-82d5-5dabb058da7d.jpeg)

وقتی یه توییت طولانی می‌شه، بخشی از متن می‌افته روی شمارنده تعداد کاراکتر باقی‌مانده

**Comment by mimalef70** [comment]
ممنون از گزارشت :) تو لیست فیکس های نسخه بعد گذاشتمش

**Comment by mimalef70** [comment]
این مشکل در بطن خود توییتر هستش. وقتی که توییت راست به چپ زده میشه کلن این مشکل وجود داره. 
<img width="571" alt="screen shot 2018-07-28 at 2 20 19 pm" src="https://user-images.githubusercontent.com/17767869/43355433-635e0ca8-9271-11e8-8292-54b87d613a27.png">
