### ISSUE TITLE
پشتیبانی از tweetdeck

### ISSUE THREAD

**Issue by MahdiZareie** [mimalef70/fontara#48]
سلام
فونت‌آرا به طور رسمی از توییتر پشتیبانی می‌کنه، اما به نظر میاد روی نسخه tweetdeck ایراداتی داره.
پشتیبانی از tweetdeck به طور رسمی وجود داره یا چون روی همون دامنه توییتر هستش فونت‌آرا فعال میشه توی صفحه؟

**Comment by mimalef70** [comment]
سلام، وقت بخیر، لطفا بیشتر توضیح بده. ممنون ☺️

**Comment by MahdiZareie** [comment]
توییتر یک کلاینت دیگه داره به نام [Tweetdeck](https://tweetdeck.twitter.com/) که روی یک ساب‌دامین از twitter.com هستش.
فونت‌آرا روی tweetdeck لود میشه و فونت‌ها رو فارسی می‌کنه اما یه سری نقص ها داره.
مثلا توی ادیتور توییت مشکل داره.
سوالم این بود که اصلا Tweetdeck رو به طور رسمی پشتیبانی می‌کنه یا نه؟

**Comment by mimalef70** [comment]
از توییت دک به صورت رسمی پشتیبانی میکنه فونت آرا. اگه جایی مشکلی دیدی
اسکرین شات بگیر بفرست برام چکش کنم. شاید چیزی از قلم افتاده. ممنون :)

**Comment by MahdiZareie** [comment]
من با ادیتوری که برای نوشتن توییت هست مشکل خورددم:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/5862289/57588294-38e1b080-7527-11e9-91f7-4e0b2f5d1ef9.png">

**Comment by mimalef70** [comment]
این مشکل در نسخه جدید برطرف شد. ممنون از ارسال گزارشتون :)
