### ISSUE TITLE
اشکال در لود فونت عنوان ایشو در گیت‌هاب

### ISSUE THREAD

**Issue by Ssisakhti** [mimalef70/fontara#5]
وقتی مستقیم این صفحه رو باز کنم
https://github.com/mimalef70/fontara/issues/1
فونت عنوان لود نمی‌شه انگار. ولی وقتی از تو لیست ایشوها برم تو همون صفحه فونت درست لود می‌شه

![fddffdfd](https://user-images.githubusercontent.com/3183983/43340001-31b42c72-91f0-11e8-9c04-4381e47ec98c.jpeg)
![dsds](https://user-images.githubusercontent.com/3183983/43340009-3623ab7a-91f0-11e8-890e-0bc1d5c40f94.jpeg)

**Comment by mimalef70** [comment]
جالبه. من میرم اکی هستش و برام این اتفاق نمیفته. این شرایط ۱۰۰ درصده ؟ یعنی همیشه که از لینک مستقیم میری اینطوره؟ شرایط واضح تری رو میتونی ارائه بدی که من هم همون کار رو بکنم و مشکل رو ببینم.

**Comment by saeedesmaili** [comment]
بله برای من هم این مشکل وجود داره و تیتر ایشو فونتش عوض نمیشه

**Comment by mimalef70** [comment]
دوستان توجه کنید که تیتیر و بعضی از قسمت ها بخاطر این که با جاوااسکریپت باید دیتکت بشن که فارسی هستن و یک کلاس بگیرن و به واسطه اون فونتشون عوض بشه. یعنی بعد از لود صفحه. شاید در همون ثانیه اول فونتشون عوض نشه. برای شما بعد از لود صفحه هم فونت تایتیل تغییری نمیکنه ؟

**Comment by saeedesmaili** [comment]
میدونم من اون مسئله رو
نه کلا صفحه لود میشه و فونت‌های مسیج‌های ایشوها عوض میشه، ولی فونت تیتر ایشو همونجوی می‌مونه

**Comment by saeedesmaili** [comment]
الان که یه کم صبر کردم، عوض شد فونتش؛ ولی خب اولا نسبتا زیاد طول کشید (حدود ۱۵ ثانیه) و اینکه چندبار دیگه هم تست کردم و فقط ده بیست درصد مواقع عوض میشه و بقیه مواقع، هر چقدر هم صبر می‌کنم عوض نمیشه
من با فایرفاکس تست میکنم
