### ISSUE TITLE
مشکل با نسخه جدید Twitter Web App

### ISSUE THREAD

**Issue by ORcxzjeeeee** [mimalef70/fontara#52]
تو بخش پروفایل کاربر قسمت نام و بایو فونت به حالت قبلی خودش هست.
![twitter](https://user-images.githubusercontent.com/29772611/60385388-e68c2d00-9a9d-11e9-91e2-1bb294f72ca4.png)

**Comment by saeedesmaili** [comment]
![image](https://user-images.githubusercontent.com/13351748/61350365-958d7e80-a87c-11e9-9a2c-96d125f8de57.png)

**Comment by mimalef70** [comment]
ممنون از ارسال گزارشتون. در نسخه جدید این مشکل بر طرف میگردد.
