### ISSUE TITLE
Google search bar direction and float

### ISSUE THREAD

**Issue by arsalanses** [mimalef70/fontara#55]
Hi there, first of all, thank you for such an amazing tool you developed ❤ great work.
Ok, this is my problem:
![Image of searchbar](http://s9.picofile.com/file/8368196218/Screenshot_2019_07_29_%D9%85%D8%AA%D9%86_%D9%86%D9%85%D9%88%D9%86%D9%87_Google_Search.png)

Is there any chance to add a feature that can recognize Persian text and change direction or float of the search bar to make it better for use?

maybe something like this
```
function check(s) {
    var PersianOrASCII = /[آ-ی]|([a-zA-Z])/;
    if ((m = s.match(PersianOrASCII)) !== null) {
        if (m[1]) {
            return false;
        } else {
            return true;
        }
    } else {
        return true;
    }
}

if(check(document.getElementsByClass("gLFyf gsfi").textContent)) {
    document.getElementsByClass("gLFyf gsfi").style.direction = "rtl";
    document.getElementsByClass("erkvQe").style.textAlign = "right";
}
```
![Image of better searchbar](http://s8.picofile.com/file/8368196984/Screenshot_2019_07_29_%D9%85%D8%AA%D9%86_%D9%86%D9%85%D9%88%D9%86%D9%87_Google_Search.png)

Thanks.

**Comment by mimalef70** [comment]
ممنون از فیدبکتون. در نسخه جدید این امکان به جستجوی گوگل اضافه میشه.
