### ISSUE TITLE
اصلاح راست به چپ در گیت‌هاب

### ISSUE THREAD

**Issue by Hameds** [mimalef70/fontara#7]
<div dir="rtl">
به نظر می‌رسه متن readme مخزن‌ها برای پیدا کردن حروف فارسی چک می‌شه و بعد اگر چیزی پیدا شد، علاوه بر تغییر فونت، راست به چپ می‌شه. چون توی متن readme ها ممکنه کد یا توضیح چپ به راست باشه، پیشنهادم اینه که یا اصلاً این بخش راست به چپ نشه (در واقع خود مدیران مخزن تصمیم بگیرن که کدام بخش از متننشون رو در markdown می‌خوان راست به چپ کنند) یا فقط پاراگراف‌های حاوی حروف فارسی راست به چپ بشوند

<img width="1100" alt="screen shot 1397-05-06 at 11 24 31" src="https://user-images.githubusercontent.com/1385656/43354009-3d3b39d2-9259-11e8-9355-df3264f22f7f.png">

</div>

**Comment by mimalef70** [comment]
باید الگوریتم این قسمت رو کلن تغییر بدم. به نظر مشکلاتی ایجاد میکنه. ممنون از گزارشت. بررسی میکنمش.

**Comment by mimalef70** [comment]
این مشکل حل شد. در اپدیت بعدی اکی میشه :)
